### ISSUE TITLE
로그 객체 생성 시 file encoding

### ISSUE THREAD

**Issue by theplan9** [haje01/loglab#2]
object command를 이용하여 log 객체 생성 시 생성된 code file의 인코딩이 euc-kr로 되어 있는데 C#의 경우 기본이 utf-8로 사용하기 때문에 utf-8로 변경을 하면 좋을 듯 합니다.

**Comment by haje01** [comment]
loglab object 명령은 표준 출력으로 코드를 보내기에, 그것을 파일로 리다이렉션 하는 과정에서 OS 환경에 따라 euc-kr 로 저장될 수 있습니다. 터미널에서 확인할 때는 현재 구현 방식이 맞겠으나, 파일로 저장할 때는 말씀대로 C# 표준인 utf-8 로 되어야 하겠습니다. 

관련하여 출력 파일을 지정하는 '--output' 옵션을 생각 중입니다. 표준 출력없이 파일에 바로 저장되며, 이때는 C#/파이썬 동히 utf-8 로 저장되는 식입니다. 작업이 진행되면 보고 하겠습니다.

**Comment by haje01** [comment]
[v0.1.6](https://github.com/haje01/loglab/tree/v0.1.6) 에서 구현되었습니다.
