### ISSUE TITLE
64비트 정수형 타입이 필요합니다.

### ISSUE THREAD

**Issue by theplan9** [haje01/loglab#3]
loglab object 기능으로 개체를 생성할 때 정수형은 integer로 지정되다 보니 64비트형 정수를 사용하는 변수를 로그에 사용할 수 없는 문제가 있습니다. 
물론 string으로 변환해서 넣으면 되지만 불편한 부분이 있어 64비트 정수형을 지원해주셨으면 합니다.

**Comment by haje01** [comment]
loglab object 명령으로 코드 생성 시, 대상 프로그램 랭귀지를 고려하여 필드에 맞는 타입을 지정하는 기능이 필요할 듯 합니다. 커스텀 타입 정의에서 관련 정보를 넣는 쪽으로 구상 중입니다. 진행되는 대로 알려드리겠습니다.

**Comment by haje01** [comment]
[v0.1.6](https://github.com/haje01/loglab/tree/v0.1.6) 에서 구현되었습니다. 자세한 것은 [문서](https://github.com/haje01/loglab#%ED%95%84%EB%93%9C%EB%B3%84-%ED%83%80%EC%9E%85-%EC%A7%80%EC%A0%95) 를 참고하세요
