### ISSUE TITLE
c#용 로그 객체 생성시 _set 변수

### ISSUE THREAD

**Issue by theplan9** [haje01/loglab#4]
c# 로그 객체 생성시에 
private Dictionary<string, bool> _set; 
이 추가 되는데 용도가 불분명합니다.

**Comment by haje01** [comment]
_set 멤버 변수는 옵션 필드에 값이 설정되었는지 저장합니다. 필수 필드와 달리 옵션 필드는 값이 지정되지 않을 수 있으며, 이런 경우 Serialize 에서 해당 필드를 출력하지 않기 위함입니다.

**Comment by haje01** [comment]
_set 멤버 변수는 옵션 필드에 값이 설정되었는지 저장하기 위해서 사용하였는데, 찿아보니 C# 의 Nullable Type 을 이용하면 없어도 될 것 같습니다. 수정 후 말씀드리겠습니다.

**Comment by haje01** [comment]
[v0.1.6](https://github.com/haje01/loglab/tree/v0.1.6) 에서 구현되었습니다.
