### ISSUE TITLE
c# 코드 생성시 DateTime Serialize오류

### ISSUE THREAD

**Issue by theplan9** [haje01/loglab#7]
DateTime 형 값을 json으로 serialize할 경우
{
     "request_time": 2022-06-21 오전 6:02:23 
}

위와 같은 형태로 추출이 되어 json 오류가 발생합니다.

**Comment by haje01** [comment]
확인해보겠습니다.  감사합니다.

**Comment by haje01** [comment]
[v0.1.7](https://github.com/haje01/loglab/tree/v0.1.7) 에서 수정되었습니다.

**Comment by haje01** [comment]
[v0.1.7](https://github.com/haje01/loglab/tree/v0.1.7) 에서 수정되었습니다.
